service: contact-serverless-miranda-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  environment:
    SECRET_KEY: ${file(.env.json):SECRET_KEY}
    URL_API: ${file(.env.json):URL_API}
  

functions:
  api:
    handler: ./lambda.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline